# Generated by Django 4.2.7 on 2023-11-16 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=256)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=1)),
                ('employment_status', models.CharField(choices=[('EM', 'Employed'), ('UN', 'Unemployed'), ('SE', 'Self-Employed'), ('ST', 'Student'), ('OT', 'Other')], max_length=2)),
                ('contact_number', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('zip', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=64)),
                ('skills', models.TextField()),
                ('cv', models.FileField(upload_to='cv')),
                ('police_report', models.FileField(upload_to='police_report')),
                ('vulnerable_sector', models.FileField(upload_to='police_report')),
                ('training_document', models.FileField(upload_to='training_report')),
                ('health_report', models.FileField(upload_to='health_report')),
                ('job_type', models.CharField(choices=[('P', 'Part-Time'), ('F', 'Full-Time')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('Name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('qualification', models.CharField(max_length=256)),
                ('date_completed', models.DateField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
