# Generated by Django 4.2.7 on 2023-11-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_identifier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
