# Generated by Django 4.2.7 on 2023-11-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_cv_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referee',
            old_name='Name',
            new_name='name',
        ),
    ]
