# Generated by Django 4.2.7 on 2023-11-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_rename_name_referee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
