# Generated by Django 4.2.7 on 2023-11-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_education_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='vulnerable_sector',
            field=models.FileField(upload_to='valnerable_sector_report'),
        ),
        migrations.AlterField(
            model_name='education',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referees', to='candidate.candidate'),
        ),
    ]
